/**
 * Nomad Shared Core - Global Error Code Registry
 * Governed by AGENTS.md Section 6: Error Code Namespacing Standard
 * Format: [MODULE]_[ACTION]_[REASON]_[3-DIGIT-INDEX]
 */

const ErrorCodes = Object.freeze({
  // Daemon lifecycle & server
  DAEMON_SERVER_PORT_IN_USE_001: 'DAEMON_SERVER_PORT_IN_USE_001',
  DAEMON_SERVER_START_FAILED_002: 'DAEMON_SERVER_START_FAILED_002',
  DAEMON_SERVER_NOT_RUNNING_003: 'DAEMON_SERVER_NOT_RUNNING_003',
  DAEMON_PROCESS_KILL_FAILED_004: 'DAEMON_PROCESS_KILL_FAILED_004',
  DAEMON_PID_READ_FAILED_005: 'DAEMON_PID_READ_FAILED_005',
  DAEMON_CLIENT_ATTACH_FAILED_006: 'DAEMON_CLIENT_ATTACH_FAILED_006',
  DAEMON_CONFIG_INVALID_007: 'DAEMON_CONFIG_INVALID_007',

  // Studio registration & handshake
  DAEMON_STUDIO_OFFLINE_001: 'DAEMON_STUDIO_OFFLINE_001',
  STUDIO_REGISTRATION_FAILED_001: 'STUDIO_REGISTRATION_FAILED_001',

  // Health probe & microservices
  PROBE_HOST_UNREACHABLE_001: 'PROBE_HOST_UNREACHABLE_001',
  PROBE_PORT_CLOSED_002: 'PROBE_PORT_CLOSED_002',
  PROBE_TIMEOUT_003: 'PROBE_TIMEOUT_003',
  PROBE_CHECK_FAILED_004: 'PROBE_CHECK_FAILED_004',

  // RPC Bridge & HTTP routing
  BRIDGE_ROUTE_NOT_FOUND_001: 'BRIDGE_ROUTE_NOT_FOUND_001',
  BRIDGE_INVALID_BODY_002: 'BRIDGE_INVALID_BODY_002',
  BRIDGE_EXECUTION_FAILED_003: 'BRIDGE_EXECUTION_FAILED_003',
  BRIDGE_INVALID_METHOD_004: 'BRIDGE_INVALID_METHOD_004',

  // Dashboard static hosting
  DASHBOARD_FILE_NOT_FOUND_001: 'DASHBOARD_FILE_NOT_FOUND_001',
  DASHBOARD_READ_FAILED_002: 'DASHBOARD_READ_FAILED_002',

  // Multi-AI Orchestrator
  ORCHESTRATOR_INVALID_SEQUENCE_001: 'ORCHESTRATOR_INVALID_SEQUENCE_001',
  ORCHESTRATOR_RUN_FAILED_002: 'ORCHESTRATOR_RUN_FAILED_002',
  ORCHESTRATOR_BUSY_003: 'ORCHESTRATOR_BUSY_003',

  // Session Manager
  SESSION_NOT_FOUND_001: 'SESSION_NOT_FOUND_001',
  SESSION_STORAGE_ERROR_002: 'SESSION_STORAGE_ERROR_002',

  // Pipeline (Headroom & Laya)
  PIPELINE_HEADROOM_COMPRESSION_FAILED_001: 'PIPELINE_HEADROOM_COMPRESSION_FAILED_001',
  PIPELINE_LAYA_DECISION_FAILED_002: 'PIPELINE_LAYA_DECISION_FAILED_002',
  PIPELINE_INVALID_INPUT_003: 'PIPELINE_INVALID_INPUT_003',

  // Google Drive Universal Sync
  SYNC_DRIVE_FOLDER_NOT_FOUND_001: 'SYNC_DRIVE_FOLDER_NOT_FOUND_001',
  SYNC_DRIVE_AUTH_FAILED_002: 'SYNC_DRIVE_AUTH_FAILED_002',
  SYNC_DRIVE_UPLOAD_FAILED_003: 'SYNC_DRIVE_UPLOAD_FAILED_003',
  SYNC_DRIVE_DOWNLOAD_FAILED_004: 'SYNC_DRIVE_DOWNLOAD_FAILED_004',
  SYNC_DRIVE_CONFLICT_005: 'SYNC_DRIVE_CONFLICT_005',
  SYNC_INVALID_PAYLOAD_006: 'SYNC_INVALID_PAYLOAD_006',

  // Shortcuts & Appearance
  SHORTCUT_REGISTRATION_FAILED_001: 'SHORTCUT_REGISTRATION_FAILED_001',
  SHORTCUT_INVALID_ACCELERATOR_002: 'SHORTCUT_INVALID_ACCELERATOR_002',
  APPEARANCE_INVALID_THEME_001: 'APPEARANCE_INVALID_THEME_001',

  // Local Model Client (P2)
  LOCAL_MODEL_UNREACHABLE_001: 'LOCAL_MODEL_UNREACHABLE_001',
  LOCAL_MODEL_INFERENCE_FAILED_002: 'LOCAL_MODEL_INFERENCE_FAILED_002',
  LOCAL_MODEL_TIMEOUT_003: 'LOCAL_MODEL_TIMEOUT_003',

  // Diff Engine (P2)
  DIFF_EXECUTION_FAILED_001: 'DIFF_EXECUTION_FAILED_001',

  // Vector Memory Lite & Hybrid Search (P2)
  MEMORY_INDEX_FAILED_001: 'MEMORY_INDEX_FAILED_001',
  MEMORY_QUERY_FAILED_002: 'MEMORY_QUERY_FAILED_002',

  // MCP Gateway (P3)
  MCP_SERVER_NOT_FOUND_001: 'MCP_SERVER_NOT_FOUND_001',
  MCP_TOOL_EXECUTION_FAILED_002: 'MCP_TOOL_EXECUTION_FAILED_002',
  MCP_INVALID_PROTOCOL_003: 'MCP_INVALID_PROTOCOL_003',

  // Knowledge Base & RAG (P3)
  RAG_DOCUMENT_READ_FAILED_001: 'RAG_DOCUMENT_READ_FAILED_001',
  RAG_CHUNKING_FAILED_002: 'RAG_CHUNKING_FAILED_002',
  RAG_RETRIEVAL_EMPTY_003: 'RAG_RETRIEVAL_EMPTY_003',

  // Plugin Runtime (P3)
  PLUGIN_MANIFEST_INVALID_001: 'PLUGIN_MANIFEST_INVALID_001',
  PLUGIN_EXECUTION_FAILED_002: 'PLUGIN_EXECUTION_FAILED_002',

  // Task Control Plane & Agent Dispatcher (Paperclip Native Integration)
  TASK_NOT_FOUND_001: "TASK_NOT_FOUND_001",
  TASK_INVALID_PAYLOAD_002: "TASK_INVALID_PAYLOAD_002",
  TASK_ALREADY_CLAIMED_003: "TASK_ALREADY_CLAIMED_003",
  TASK_INVALID_STATE_TRANSITION_004: "TASK_INVALID_STATE_TRANSITION_004",
  TASK_DEPENDENCY_UNRESOLVED_005: "TASK_DEPENDENCY_UNRESOLVED_005",
  TASK_HEARTBEAT_EXPIRED_006: "TASK_HEARTBEAT_EXPIRED_006",
  TASK_EXECUTION_FAILED_007: "TASK_EXECUTION_FAILED_007",
  TASK_STORAGE_SAVE_FAILED_008: "TASK_STORAGE_SAVE_FAILED_008",
  TASK_STORAGE_LOAD_FAILED_009: "TASK_STORAGE_LOAD_FAILED_009",
  ROSTER_AGENT_NOT_FOUND_001: "ROSTER_AGENT_NOT_FOUND_001",
  ROSTER_INVALID_PROFILE_002: "ROSTER_INVALID_PROFILE_002",
  APPROVAL_GATE_NOT_PENDING_001: "APPROVAL_GATE_NOT_PENDING_001",
  APPROVAL_ACTION_INVALID_002: "APPROVAL_ACTION_INVALID_002",
  TASK_SCHEDULE_INVALID_010: "TASK_SCHEDULE_INVALID_010",
  TASK_SCHEDULE_NOT_FOUND_011: "TASK_SCHEDULE_NOT_FOUND_011",
});

module.exports = {
  ErrorCodes
};
