/**
 * Nomad Shared Core - Global Error Code Registry
 * Governed by AGENTS.md Section 6: Error Code Namespacing Standard
 * Format: [MODULE]_[ACTION]_[REASON]_[3-DIGIT-INDEX]
 */

const ErrorCodes = Object.freeze({
  // Daemon lifecycle & server
  DAEMON_SERVER_PORT_IN_USE_001: 'DAEMON_SERVER_PORT_IN_USE_001',
  DAEMON_SERVER_START_FAILED_002: 'DAEMON_SERVER_START_FAILED_002',
  DAEMON_SERVER_NOT_RUNNING_003: 'DAEMON_SERVER_NOT_RUNNING_003',
  DAEMON_PROCESS_KILL_FAILED_004: 'DAEMON_PROCESS_KILL_FAILED_004',
  DAEMON_PID_READ_FAILED_005: 'DAEMON_PID_READ_FAILED_005',
  DAEMON_CLIENT_ATTACH_FAILED_006: 'DAEMON_CLIENT_ATTACH_FAILED_006',
  DAEMON_CONFIG_INVALID_007: 'DAEMON_CONFIG_INVALID_007',

  // Studio registration & handshake
  DAEMON_STUDIO_OFFLINE_001: 'DAEMON_STUDIO_OFFLINE_001',
  STUDIO_REGISTRATION_FAILED_001: 'STUDIO_REGISTRATION_FAILED_001',

  // Health probe & microservices
  PROBE_HOST_UNREACHABLE_001: 'PROBE_HOST_UNREACHABLE_001',
  PROBE_PORT_CLOSED_002: 'PROBE_PORT_CLOSED_002',
  PROBE_TIMEOUT_003: 'PROBE_TIMEOUT_003',
  PROBE_CHECK_FAILED_004: 'PROBE_CHECK_FAILED_004',

  // RPC Bridge & HTTP routing
  BRIDGE_ROUTE_NOT_FOUND_001: 'BRIDGE_ROUTE_NOT_FOUND_001',
  BRIDGE_INVALID_BODY_002: 'BRIDGE_INVALID_BODY_002',
  BRIDGE_EXECUTION_FAILED_003: 'BRIDGE_EXECUTION_FAILED_003',
  BRIDGE_INVALID_METHOD_004: 'BRIDGE_INVALID_METHOD_004',

  // Dashboard static hosting
  DASHBOARD_FILE_NOT_FOUND_001: 'DASHBOARD_FILE_NOT_FOUND_001',
  DASHBOARD_READ_FAILED_002: 'DASHBOARD_READ_FAILED_002',

  // Multi-AI Orchestrator
  ORCHESTRATOR_INVALID_SEQUENCE_001: 'ORCHESTRATOR_INVALID_SEQUENCE_001',
  ORCHESTRATOR_RUN_FAILED_002: 'ORCHESTRATOR_RUN_FAILED_002',
  ORCHESTRATOR_BUSY_003: 'ORCHESTRATOR_BUSY_003',

  // Session Manager
  SESSION_NOT_FOUND_001: 'SESSION_NOT_FOUND_001',
  SESSION_STORAGE_ERROR_002: 'SESSION_STORAGE_ERROR_002',

  // Pipeline (Headroom & Laya)
  PIPELINE_HEADROOM_COMPRESSION_FAILED_001: 'PIPELINE_HEADROOM_COMPRESSION_FAILED_001',
  PIPELINE_LAYA_DECISION_FAILED_002: 'PIPELINE_LAYA_DECISION_FAILED_002',
  PIPELINE_INVALID_INPUT_003: 'PIPELINE_INVALID_INPUT_003',

  // Google Drive Universal Sync
  SYNC_DRIVE_FOLDER_NOT_FOUND_001: 'SYNC_DRIVE_FOLDER_NOT_FOUND_001',
  SYNC_DRIVE_AUTH_FAILED_002: 'SYNC_DRIVE_AUTH_FAILED_002',
  SYNC_DRIVE_UPLOAD_FAILED_003: 'SYNC_DRIVE_UPLOAD_FAILED_003',
  SYNC_DRIVE_DOWNLOAD_FAILED_004: 'SYNC_DRIVE_DOWNLOAD_FAILED_004',
  SYNC_DRIVE_CONFLICT_005: 'SYNC_DRIVE_CONFLICT_005',
  SYNC_INVALID_PAYLOAD_006: 'SYNC_INVALID_PAYLOAD_006',

  // Shortcuts & Appearance
  SHORTCUT_REGISTRATION_FAILED_001: 'SHORTCUT_REGISTRATION_FAILED_001',
  SHORTCUT_INVALID_ACCELERATOR_002: 'SHORTCUT_INVALID_ACCELERATOR_002',
  APPEARANCE_INVALID_THEME_001: 'APPEARANCE_INVALID_THEME_001',
});

module.exports = {
  ErrorCodes
};
