/**
 * Nomad Shared Core - Global Error Code Registry
 * Governed by AGENTS.md Section 6: Error Code Namespacing Standard
 * Format: [MODULE]_[ACTION]_[REASON]_[3-DIGIT-INDEX]
 */

const ErrorCodes = Object.freeze({
  // Daemon lifecycle & server
  DAEMON_SERVER_PORT_IN_USE_001: 'DAEMON_SERVER_PORT_IN_USE_001',
  DAEMON_SERVER_START_FAILED_002: 'DAEMON_SERVER_START_FAILED_002',
  DAEMON_SERVER_NOT_RUNNING_003: 'DAEMON_SERVER_NOT_RUNNING_003',
  DAEMON_PROCESS_KILL_FAILED_004: 'DAEMON_PROCESS_KILL_FAILED_004',
  DAEMON_PID_READ_FAILED_005: 'DAEMON_PID_READ_FAILED_005',
  DAEMON_CLIENT_ATTACH_FAILED_006: 'DAEMON_CLIENT_ATTACH_FAILED_006',
  DAEMON_CONFIG_INVALID_007: 'DAEMON_CONFIG_INVALID_007',

  // Health probe & microservices
  PROBE_HOST_UNREACHABLE_001: 'PROBE_HOST_UNREACHABLE_001',
  PROBE_PORT_CLOSED_002: 'PROBE_PORT_CLOSED_002',
  PROBE_TIMEOUT_003: 'PROBE_TIMEOUT_003',
  PROBE_CHECK_FAILED_004: 'PROBE_CHECK_FAILED_004',

  // RPC Bridge & HTTP routing
  BRIDGE_ROUTE_NOT_FOUND_001: 'BRIDGE_ROUTE_NOT_FOUND_001',
  BRIDGE_INVALID_BODY_002: 'BRIDGE_INVALID_BODY_002',
  BRIDGE_EXECUTION_FAILED_003: 'BRIDGE_EXECUTION_FAILED_003',
  BRIDGE_INVALID_METHOD_004: 'BRIDGE_INVALID_METHOD_004',

  // Dashboard static hosting
  DASHBOARD_FILE_NOT_FOUND_001: 'DASHBOARD_FILE_NOT_FOUND_001',
  DASHBOARD_READ_FAILED_002: 'DASHBOARD_READ_FAILED_002',

  // Multi-AI Orchestrator
  ORCHESTRATOR_INVALID_SEQUENCE_001: 'ORCHESTRATOR_INVALID_SEQUENCE_001',
  ORCHESTRATOR_RUN_FAILED_002: 'ORCHESTRATOR_RUN_FAILED_002',
  ORCHESTRATOR_BUSY_003: 'ORCHESTRATOR_BUSY_003',

  // Session Manager
  SESSION_NOT_FOUND_001: 'SESSION_NOT_FOUND_001',
  SESSION_STORAGE_ERROR_002: 'SESSION_STORAGE_ERROR_002'
});

module.exports = {
  ErrorCodes
};
