export type UnitSuccess<T> = import("./src/result").UnitSuccess<T>;
export type UnitFailure<E = string> = import("./src/result").UnitFailure<E>;
export type UnitResult<T, E = string> = import("./src/result").UnitResult<T, E>;
export type ErrorCode = import("./src/error-codes").ErrorCode;
export type Bot = import("./src/bots/bot-roster").Bot;
export type BotServices = import("./src/bots/bot-routes").BotServices;
export type MonitoredService = import("./src/constants").MonitoredService;
export type PlatformConfig = import("./src/constants").PlatformConfig;
export type TemplateVariable = import("./src/extensions/template-parser").TemplateVariable;
export type ChatMessage = import("./src/extensions/markdown-exporter").ChatMessage;
export type ChatExportOptions = import("./src/extensions/markdown-exporter").ChatExportOptions;
import { ok } from "./src/result";
import { err } from "./src/result";
import { isOk } from "./src/result";
import { isErr } from "./src/result";
import { wrapAsync } from "./src/result";
import { ErrorCodes } from "./src/error-codes";
import { DEFAULT_DAEMON_PORT } from "./src/constants";
import { DEFAULT_DAEMON_HOST } from "./src/constants";
import { MONITORED_SERVICES } from "./src/constants";
import { PLATFORMS } from "./src/constants";
import { LAYOUTS } from "./src/constants";
import { SEMANTIC_TYPES } from "./src/constants";
import { extractVariables } from "./src/extensions/template-parser";
import { interpolate } from "./src/extensions/template-parser";
import { formatChatToMarkdown } from "./src/extensions/markdown-exporter";
import { estimateTokens } from "./src/pipeline/headroom";
import { compress } from "./src/pipeline/headroom";
import { decide } from "./src/pipeline/laya";
import { PipelineManager } from "./src/pipeline/index";
import { DRIVE_FOLDER_NAME } from "./src/sync/universal-drive-sync";
import { WORKSPACES_FILE_NAME } from "./src/sync/universal-drive-sync";
import { SETTINGS_FILE_NAME } from "./src/sync/universal-drive-sync";
import { MANIFEST_FILE_NAME } from "./src/sync/universal-drive-sync";
import { detectLocalDriveFolder } from "./src/sync/universal-drive-sync";
import { computeChecksum } from "./src/sync/universal-drive-sync";
import { exportToDrive } from "./src/sync/universal-drive-sync";
import { importFromDrive } from "./src/sync/universal-drive-sync";
import { getSyncStatus } from "./src/sync/universal-drive-sync";
import { ARTIFACT_TYPES } from "./src/canvas/artifact-extractor";
import { extractArtifacts } from "./src/canvas/artifact-extractor";
import { generateSandboxHtml } from "./src/canvas/artifact-extractor";
export namespace ArtifactExtractor {
    export { extractArtifacts as extract };
    export { extractArtifacts };
    export { generateSandboxHtml };
}
export namespace DiffEngine {
    export { computeDiff as diffLines };
    export { computeDiff };
}
import { LocalModelClient } from "./src/client/local-model-client";
import { computeDiff } from "./src/diff/diff-engine";
import { tokenize } from "./src/memory/vector-memory-lite";
import { VectorMemoryLite } from "./src/memory/vector-memory-lite";
import { McpGateway } from "./src/mcp/mcp-gateway";
import { ALLOWED_PATHS_ENV as MCP_ALLOWED_PATHS_ENV } from "./src/mcp/mcp-gateway";
import { defaultAllowedPaths } from "./src/mcp/mcp-gateway";
import { defaultDeniedPaths } from "./src/mcp/mcp-gateway";
import { KnowledgeBase } from "./src/rag/knowledge-base";
import { PluginRuntime } from "./src/plugins/plugin-runtime";
import { TASK_STATUS } from "./src/tasks/index";
import { TASK_PRIORITY } from "./src/tasks/index";
import { validateTransition } from "./src/tasks/index";
import { createTaskEntity } from "./src/tasks/index";
import { AGENT_STATUS } from "./src/tasks/index";
import { DEFAULT_ROSTER } from "./src/tasks/index";
import { AgentRoster } from "./src/tasks/index";
import { TaskDispatcher } from "./src/tasks/index";
import { ApprovalGate } from "./src/tasks/index";
import { TaskRunner } from "./src/tasks/index";
import { RecurringScheduler } from "./src/tasks/index";
import { DEFAULT_PRESET_SCHEDULES } from "./src/tasks/index";
import { BOT_STATE } from "./src/bots/index";
import { DEFAULT_ROSTER_PATH } from "./src/bots/index";
import { BotRoster } from "./src/bots/index";
import { toBotHandle } from "./src/bots/index";
import { handleBotRequest } from "./src/bots/index";
import { NEW_CHAT_URLS } from "./src/bots/index";
import { normalizeChatUrl } from "./src/bots/index";
import { isConversationUrl } from "./src/bots/index";
import { isSameConversation } from "./src/bots/index";
import { probePort } from "./src/probe/prober";
import { probeAllServices } from "./src/probe/prober";
import { resolveAuthToken } from "./src/security/local-auth";
import { getTokenFilePath } from "./src/security/local-auth";
import { isLoopbackHostname } from "./src/security/local-auth";
import { isLoopbackModelTarget } from "./src/security/local-auth";
import { applyCorsHeaders } from "./src/security/local-auth";
import { authorizeRequest } from "./src/security/local-auth";
import { injectDashboardAuth } from "./src/security/local-auth";
export { ok, err, isOk, isErr, wrapAsync, ErrorCodes, DEFAULT_DAEMON_PORT, DEFAULT_DAEMON_HOST, MONITORED_SERVICES, PLATFORMS, LAYOUTS, SEMANTIC_TYPES, extractVariables, interpolate, formatChatToMarkdown, estimateTokens, compress, decide, PipelineManager, DRIVE_FOLDER_NAME, WORKSPACES_FILE_NAME, SETTINGS_FILE_NAME, MANIFEST_FILE_NAME, detectLocalDriveFolder, computeChecksum, exportToDrive, importFromDrive, getSyncStatus, ARTIFACT_TYPES, extractArtifacts, generateSandboxHtml, LocalModelClient, computeDiff, tokenize, VectorMemoryLite, McpGateway, MCP_ALLOWED_PATHS_ENV, defaultAllowedPaths, defaultDeniedPaths, KnowledgeBase, PluginRuntime, TASK_STATUS, TASK_PRIORITY, validateTransition, createTaskEntity, AGENT_STATUS, DEFAULT_ROSTER, AgentRoster, TaskDispatcher, ApprovalGate, TaskRunner, RecurringScheduler, DEFAULT_PRESET_SCHEDULES, BOT_STATE, DEFAULT_ROSTER_PATH, BotRoster, toBotHandle, handleBotRequest, NEW_CHAT_URLS, normalizeChatUrl, isConversationUrl, isSameConversation, probePort, probeAllServices, resolveAuthToken, getTokenFilePath, isLoopbackHostname, isLoopbackModelTarget, applyCorsHeaders, authorizeRequest, injectDashboardAuth };
